### ISSUE TITLE
Logo for AGallery

### ISSUE THREAD

**Issue by hafizahmmed** [aakashswain001/AGallery#4]
Hello,
Good Day, i make a logo icon for your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![agallery-01](https://user-images.githubusercontent.com/38810169/40102056-426f995c-590b-11e8-967f-11b469655ff9.png)

**Comment by aakashswain001** [comment]
Thank you @hafizahmmed 
This is my current logo. App theme is based on these colours .So if you can make a logo of this colour it will be nice.
![ic_launcher](https://user-images.githubusercontent.com/23445811/40276243-947dae0e-5c22-11e8-8388-5a75b2180afc.png)

**Comment by hafizahmmed** [comment]
please check this

![agallery-01](https://user-images.githubusercontent.com/38810169/40276377-5fac95b6-5c2a-11e8-957a-830342c8d0c5.jpg)

**Comment by aakashswain001** [comment]
This would be nice. Doing in photoshop? I need them in diff resolutions.

**Comment by hafizahmmed** [comment]
I make this logo use adobe illustrator cc 2018

give me the size requirement for the icon. Which one do you want right side or left side??

i provided you all source file.

**Comment by aakashswain001** [comment]
http://iconhandbook.co.uk/reference/chart/android/

Link to android icon sizes. 

I think right side is looking good. 

I also need a feature graphic and promo graphic for playstore
Size
Feature
JPEG or 24-bit PNG (no alpha)
Dimensions: 1024px by 500px
Promo
JPG or 24-bit PNG (no alpha)
Dimensions: 180px by 120px

Playstore link
https://play.google.com/store/apps/details?id=xyz.sleepygamers.agallery

**Comment by aakashswain001** [comment]
In the link see the launcher icon sizes. Others are not needed

**Comment by hafizahmmed** [comment]
plzz check here https://drive.google.com/open?id=1AlUDZMtk9FiJntZvcxO5cdQiJistWlyW

anything change comment blow.

**Comment by aakashswain001** [comment]
Everything looks good. If you can change the feature image

**Comment by hafizahmmed** [comment]
Which type you need feature image? 
Like promo?

**Comment by hafizahmmed** [comment]
![feature2](https://user-images.githubusercontent.com/38810169/40296824-a3b0cf54-5cff-11e8-9da2-04ce3702375e.png)

**Comment by aakashswain001** [comment]
Yes thank you. this will work

**Comment by hafizahmmed** [comment]
when you add this in your project?

**Comment by aakashswain001** [comment]
This week.

**Comment by hafizahmmed** [comment]
thankyou for add my icon.
